# This will start a haproxy and 10 web services. haproxy will act as a loadbalancer.
# Authors: lukas.pavelka@gmail.com
# Date: 2022-01-15

weba:
    build: ./web
    expose:
        - 80

webb:
    build: ./web
    expose:
        - 80

webc:
    build: ./web
    expose:
        - 80

webd:
    build: ./web
    expose:
        - 80

webe:
    build: ./web
    expose:
        - 80

webf:
    build: ./web
    expose:
        - 80

webg:
    build: ./web
    expose:
        - 80

webh:
    build: ./web
    expose:
        - 80

webi:
    build: ./web
    expose:
        - 80

webj:
    build: ./web
    expose:
        - 80

haproxy:
    image: haproxy:1.6
    volumes:
        - ./haproxy:/haproxy-override
        - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    links:
        - weba
        - webb
        - webc
        - webd
        - webe
        - webf
        - webg
        - webh
        - webi
        - webj
    ports:
        - "80:80"
        - "70:70"
